def dqn_arguments(parser):
	parser.add_argument('--seed', default=11037, type=int)
	parser.add_argument('--episodes', default=200, type=int)
	parser.add_argument('--batch_size', default=128, type=int)
	parser.add_argument('--hidden_size', default=128, type=int)
	parser.add_argument('--lr', default=5e-4, type=float)
	parser.add_argument('--gamma', default=0.99, type=float)
	parser.add_argument('--grad_norm_clip', default=10, type=float)
	parser.add_argument('--buffer_size', default=20000, type=int)
	parser.add_argument('--eps_start', default=1.0, type=float)
	parser.add_argument('--eps_end', default=0.05, type=float)
	parser.add_argument('--eps_decay', default=1000, type=int)
	parser.add_argument('--update_freq', default=100, type=int)
	parser.add_argument('--test', default=True, type=bool)
	parser.add_argument('--device', default='cuda', type=str)
	parser.add_argument('--output_dir', default='C:/Temp/dqn', type=str)
	parser.add_argument('--save_model', default=True, type=bool)
	parser.add_argument('--model_path', default='C:/Temp/dqn/model.pth', type=str)
	return parser
